import { Trash2 } from 'lucide-react';

export default function DeleteRecurringModal({ isOpen, onClose, onConfirm, templateTitle, isLoading }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm" onClick={onClose} />
      
      <div className="relative bg-slate-900 border border-slate-800 rounded-2xl p-6 max-w-sm w-full shadow-xl space-y-6">
        <div className="flex items-start gap-3">
          <div className="p-2 bg-red-500/10 border border-red-500/20 text-red-400 rounded-xl">
            <Trash2 className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white">Delete Recurring Schedule</h3>
            <p className="text-xs text-slate-400 mt-1">
              Are you sure you want to delete the recurring expense <span className="font-semibold text-slate-200">"{templateTitle}"</span>?
            </p>
            <p className="text-[10px] text-slate-500 mt-2 leading-relaxed">
              This action stops all future automatic generations. Existing expenses generated by this template will remain intact.
            </p>
          </div>
        </div>

        {/* Controls */}
        <div className="flex items-center gap-3">
          <button
            onClick={onClose}
            disabled={isLoading}
            className="flex-1 py-2 px-4 bg-slate-950/40 hover:bg-slate-950/80 text-slate-400 hover:text-slate-200 text-xs font-bold border border-slate-850 rounded-xl transition cursor-pointer"
          >
            Cancel
          </button>
          <button
            onClick={onConfirm}
            disabled={isLoading}
            className="flex-1 flex items-center justify-center space-x-1.5 py-2 px-4 bg-red-650 hover:bg-red-650/80 disabled:opacity-50 text-white text-xs font-bold rounded-xl transition cursor-pointer"
          >
            {isLoading ? (
              <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
            ) : (
              <span>Delete Schedule</span>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
