import { useEffect } from 'react';
import { useAnalyticsStore } from '../store/analyticsStore';
import { useCurrencyStore } from '../store/currencyStore';
import { ForecastChart, ForecastConfidenceBadge, BudgetProgressBar } from '../components/analytics';
import {
  TrendingUp,
  Sparkles,
  Shield,
  Calendar,
  AlertTriangle,
  Clock,
  ArrowRight,
  TrendingDown,
  Activity,
  ChevronRight
} from 'lucide-react';
import { motion } from 'framer-motion';

export default function ForecastPage() {
  const {
    forecast,
    budgets,
    isLoading,
    error,
    fetchForecast,
    fetchBudgets
  } = useAnalyticsStore();

  const { formatCurrency, preferredCurrency } = useCurrencyStore();

  useEffect(() => {
    fetchForecast();
    fetchBudgets();
  }, [fetchForecast, fetchBudgets]);

  const now = new Date();
  const formatVal = (cents) => {
    const converted = useCurrencyStore.getState().convertAmount(cents, 'INR', preferredCurrency);
    return formatCurrency(converted, preferredCurrency);
  };

  return (
    <div className="space-y-8 text-slate-100 font-sans">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-black tracking-tight text-white mb-2 flex items-center gap-2">
          <Sparkles className="w-8 h-8 text-indigo-500 animate-pulse" />
          <span>Spending Forecasts</span>
        </h1>
        <p className="text-slate-400 text-sm">
          Fitted Linear Regression spending projections, explainers, and budget exhaustion timelines.
        </p>
      </div>

      {error && (
        <div className="p-4 bg-red-950/40 border border-red-800/60 rounded-2xl text-red-300 text-sm">
          {error}
        </div>
      )}

      {/* Main Forecast Chart Card */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 bg-slate-900/60 border border-slate-800 rounded-2xl p-6 shadow-lg">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6">
            <div>
              <h3 className="text-lg font-bold text-white flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-indigo-400" />
                <span>30-Day Projections</span>
              </h3>
              <p className="text-xs text-slate-400 mt-1">Daily spent forecasts generated by Linear Regression.</p>
            </div>
            {forecast && (
              <ForecastConfidenceBadge confidence={forecast.confidence} />
            )}
          </div>

          <ForecastChart forecast={forecast?.forecast} />
        </div>

        {/* Explainability metadata card */}
        <div className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 shadow-lg space-y-6">
          <h3 className="text-lg font-bold text-white flex items-center gap-2">
            <Shield className="w-5 h-5 text-indigo-400" />
            <span>Explainability Diagnostics</span>
          </h3>

          <div className="grid grid-cols-2 gap-4">
            <div className="p-4 bg-slate-950 border border-slate-800/60 rounded-xl">
              <span className="text-[10px] text-slate-400 uppercase tracking-wider block mb-1">Expected Daily Avg</span>
              <span className="text-lg font-black text-white">{formatVal(forecast?.expectedDailyAverage || 0)}</span>
            </div>
            <div className="p-4 bg-slate-950 border border-slate-800/60 rounded-xl">
              <span className="text-[10px] text-slate-400 uppercase tracking-wider block mb-1">Expected Monthly</span>
              <span className="text-lg font-black text-white">{formatVal(forecast?.expectedMonthlySpend || 0)}</span>
            </div>
            <div className="p-4 bg-slate-950 border border-slate-800/60 rounded-xl">
              <span className="text-[10px] text-slate-400 uppercase tracking-wider block mb-1">Fitted Trend</span>
              <span className="text-lg font-black text-indigo-400 flex items-center gap-1">
                {forecast?.trend === 'Increasing' ? (
                  <TrendingUp className="w-4 h-4 text-rose-400" />
                ) : (
                  <TrendingDown className="w-4 h-4 text-emerald-400" />
                )}
                <span>{forecast?.trend || 'Stable'}</span>
              </span>
            </div>
            <div className="p-4 bg-slate-950 border border-slate-800/60 rounded-xl">
              <span className="text-[10px] text-slate-400 uppercase tracking-wider block mb-1">Data Points Used</span>
              <span className="text-lg font-black text-white">{forecast?.dataPointsUsed || 0}</span>
            </div>
          </div>

          <div className="p-4 bg-slate-950/60 border border-slate-800/80 rounded-xl space-y-3 text-xs text-slate-400">
            <div className="flex justify-between">
              <span>Model Slope:</span>
              <span className="font-mono text-white">{(forecast?.regressionSlope || 0).toFixed(4)}</span>
            </div>
            <div className="flex justify-between">
              <span>Model Intercept:</span>
              <span className="font-mono text-white">{(forecast?.regressionIntercept || 0).toFixed(2)}</span>
            </div>
            <div className="flex justify-between">
              <span>Model Version:</span>
              <span className="font-mono text-white">{forecast?.modelVersion}</span>
            </div>
            <div className="flex justify-between">
              <span>Forecast Method:</span>
              <span className="font-mono text-white">{forecast?.forecastMethod}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Forecast Budget Integration: exhaustion timelines */}
      <div className="bg-slate-900/60 border border-slate-800 rounded-2xl p-6 shadow-lg">
        <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2">
          <Clock className="w-5 h-5 text-indigo-400" />
          <span>Estimated Budget Exhaustion Timelines</span>
        </h3>

        {budgets.length === 0 ? (
          <div className="text-center py-8 text-slate-500 text-sm italic">
            No active budgets setup yet.
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {budgets.map((b) => {
              const spent = b.spentAmount;
              const limit = b.amount;
              const remaining = limit - spent;
              
              // Calculate exhaustion
              let exhaustionText = 'Stable — No exhaustion predicted.';
              let daysRemaining = Infinity;
              let warning = false;

              const dailyAvg = forecast?.expectedDailyAverage || 0;
              if (spent >= limit) {
                exhaustionText = 'Budget has already been exceeded!';
                warning = true;
              } else if (dailyAvg > 0) {
                // convert remaining (in budget currency) to base currency (INR cents)
                // dailyAvg is in base currency (INR cents)
                const remainingBase = useCurrencyStore.getState().convertAmount(remaining, b.currency, 'INR');
                daysRemaining = Math.ceil(remainingBase / dailyAvg);
                
                const exhaustionDate = new Date(now.getTime() + daysRemaining * 24 * 60 * 60 * 1000);
                exhaustionText = `Exhaustion predicted on ${exhaustionDate.toLocaleDateString()} (${daysRemaining} days remaining).`;
                if (daysRemaining <= 7) warning = true;
              }

              return (
                <div key={b.id} className="p-5 bg-slate-950/80 border border-slate-800/80 rounded-xl space-y-4 relative overflow-hidden group">
                  <div className="flex justify-between items-start">
                    <div>
                      <h4 className="text-sm font-bold text-white uppercase tracking-wider">{b.period} {b.category || 'OVERALL'}</h4>
                      <span className="text-[10px] text-slate-500">Currency: {b.currency}</span>
                    </div>
                    {warning && (
                      <span className="p-1.5 bg-red-950/60 border border-red-800 rounded-lg text-red-400">
                        <AlertTriangle className="w-4 h-4" />
                      </span>
                    )}
                  </div>

                  <BudgetProgressBar spent={spent} limit={limit} currency={b.currency} />

                  <div className="flex items-center gap-2 text-xs">
                    <ChevronRight className="w-4 h-4 text-indigo-400" />
                    <span className={warning ? 'text-red-400 font-medium' : 'text-slate-400'}>
                      {exhaustionText}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
